'use client';

import { useState, useEffect } from 'react';
import { useTranslation } from '../../lib/useTranslation';

export default function PaymentDetails() {
  const [language, setLanguage] = useState<'en' | 'hi'>('en');
  const { t } = useTranslation(language);
  const [isDarkTheme, setIsDarkTheme] = useState(false);
  const [workerData, setWorkerData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [showBankForm, setShowBankForm] = useState(false);
  const [bankDetails, setBankDetails] = useState({
    bankName: '',
    accountNumber: '',
    ifscCode: '',
    branchName: ''
  });
  const [isUpdating, setIsUpdating] = useState(false);

  useEffect(() => {
    // Check if worker is logged in
    const isWorker = localStorage.getItem('isWorker');
    const workerDataStr = localStorage.getItem('workerData');
    
    if (!isWorker || !workerDataStr) {
      // Redirect to login if not logged in
      window.location.href = '/auth';
      return;
    }
    
    try {
      const data = JSON.parse(workerDataStr);
      setWorkerData(data);
      // Pre-fill bank details if available
      if (data.bank_details) {
        setBankDetails({
          bankName: data.bank_details.bank_name || '',
          accountNumber: data.bank_details.account_number || '',
          ifscCode: data.bank_details.ifsc_code || '',
          branchName: data.bank_details.branch_name || ''
        });
      }
    } catch (error) {
      console.error('Error parsing worker data:', error);
      window.location.href = '/auth';
    }
    
    setLoading(false);
  }, []);

  const toggleTheme = () => setIsDarkTheme(!isDarkTheme);
  const toggleLanguage = () => setLanguage(language === 'en' ? 'hi' : 'en');

  const formatDate = (dateString: string) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('en-IN', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    });
  };

  const formatDateTime = (dateString: string) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleString('en-IN', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const handleLogout = () => {
    localStorage.removeItem('workerData');
    localStorage.removeItem('isWorker');
    window.location.href = '/auth';
  };

  const generatePaymentReport = () => {
    const paidProjects = workerData?.work_history?.filter((w: any) => w.status === 'completed' || w.status === 'paid') || [];
    const totalAmount = paidProjects.reduce((sum: number, project: any) => sum + (project.wage_per_worker || project.wage || 0), 0);
    
    let report = `GOVERNMENT OF INDIA
`;
    report += `MINISTRY OF RURAL DEVELOPMENT
`;
    report += `PAYMENT HISTORY REPORT
`;
    report += `National Rural Employment Guarantee Act, 2005

`;
    report += `WORKER DETAILS
`;
    report += `Name: ${workerData?.name || 'N/A'}
`;
    report += `Job Card ID: ${workerData?.job_card_id || 'N/A'}
`;
    report += `Aadhaar Number: ${workerData?.aadhaar_number || 'N/A'}

`;
    report += `Generated by Smart Rozgar Portal - MGNREGA Inspired System

`;
    report += `Sr.No	Project			Days Worked	Wage/Day	Total Amount	Project End Date	Status
`;
    report += `-----	-------			-----------	--------	------------	----------------	------
`;
    
    paidProjects.forEach((project: any, index: number) => {
      const projectName = (project.name || project.project_name || 'Unnamed Project').substring(0, 20);
      const daysWorked = project.days_worked || 1;
      const wagePerDay = project.wage_per_worker || project.wage || 0;
      const totalAmount = daysWorked * wagePerDay;
      const endDate = formatDate(project.end_date);
      
      report += `${index + 1}	${projectName}${''.padEnd(20 - projectName.length)}	${daysWorked}		₹${wagePerDay}.00	₹${totalAmount}.00		${endDate}		PAID
`;
    });
    
    report += `
SUMMARY
`;
    report += `Total Payments: ${paidProjects.length}
`;
    report += `Total Amount: ₹${totalAmount}.00
`;
    report += `Paid: ${paidProjects.length}
`;
    report += `Pending: ${(workerData?.work_history?.length || 0) - paidProjects.length}

`;
    report += `Certified that the above information is true and correct

`;
    report += `Authorized Signatory:
`;
    report += `Page 1 of 1`;
    
    return report;
  };

  const handleBankDetailsChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setBankDetails(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleUpdateBankDetails = async () => {
    if (!bankDetails.bankName || !bankDetails.accountNumber || !bankDetails.ifscCode) {
      alert('Please fill in all required bank details');
      return;
    }

    setIsUpdating(true);
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      // Update local storage
      const updatedWorkerData = {
        ...workerData,
        bank_details: bankDetails
      };
      localStorage.setItem('workerData', JSON.stringify(updatedWorkerData));
      setWorkerData(updatedWorkerData);
      
      alert('Bank details updated successfully!');
      setShowBankForm(false);
    } catch (error) {
      console.error('Error updating bank details:', error);
      alert('Failed to update bank details. Please try again.');
    } finally {
      setIsUpdating(false);
    }
  };

  // Calculate monthly totals
  const calculateMonthlyTotals = () => {
    if (!workerData?.work_history) return [];
    
    const monthlyData: any = {};
    
    workerData.work_history.forEach((work: any) => {
      if (work.status === 'completed' || work.status === 'paid') {
        const date = new Date(work.end_date);
        const monthKey = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
        const monthName = date.toLocaleString('en-IN', { month: 'long', year: 'numeric' });
        
        if (!monthlyData[monthKey]) {
          monthlyData[monthKey] = {
            month: monthName,
            totalAmount: 0,
            projects: 0
          };
        }
        
        monthlyData[monthKey].totalAmount += work.wage_per_worker || work.wage || 0;
        monthlyData[monthKey].projects += 1;
      }
    });
    
    return Object.values(monthlyData).sort((a: any, b: any) => 
      new Date(b.month).getTime() - new Date(a.month).getTime()
    );
  };

  const monthlyTotals = calculateMonthlyTotals();

  if (loading) {
    return (
      <div className={`min-h-screen flex items-center justify-center ${isDarkTheme ? 'bg-gray-900' : 'bg-indigo-50'}`}>
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading payment details...</p>
        </div>
      </div>
    );
  }

  return (
    <div className={`min-h-screen ${isDarkTheme ? 'bg-gray-900 text-white' : 'bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 text-gray-900'}`}>
      {/* Header */}
      <header className={`py-5 px-6 flex items-center justify-between ${isDarkTheme ? 'bg-gray-900/90 backdrop-blur-lg shadow-lg' : 'bg-white/90 backdrop-blur-lg shadow-lg'} transition-colors duration-300`}>
        <button 
          onClick={() => window.location.href = '/worker/dashboard'}
          className="text-2xl font-extrabold bg-gradient-to-r from-indigo-700 to-purple-700 bg-clip-text text-transparent select-none hover:opacity-80 transition-opacity"
        >
          Payment Details
        </button>
        <div className="flex items-center space-x-5">
          <button 
            onClick={toggleTheme}
            className={`px-5 py-2 rounded-lg font-semibold shadow-md transform transition-transform duration-300 ease-in-out ${
              isDarkTheme 
                ? 'bg-indigo-700 text-white hover:bg-indigo-800 hover:shadow-xl hover:scale-105' 
                : 'bg-indigo-100 text-indigo-700 hover:bg-indigo-200 hover:shadow-lg hover:scale-105'
            }`}
          >
            {isDarkTheme ? 'Light Mode' : 'Dark Mode'}
          </button>
          
          <button 
            onClick={toggleLanguage}
            className={`px-5 py-2 rounded-lg font-semibold shadow-md transform transition-transform duration-300 ease-in-out ${
              isDarkTheme 
                ? 'bg-purple-700 text-white hover:bg-purple-800 hover:shadow-xl hover:scale-105' 
                : 'bg-purple-100 text-purple-700 hover:bg-purple-200 hover:shadow-lg hover:scale-105'
            }`}
          >
            {language === 'en' ? 'हिंदी' : 'English'}
          </button>
          
          <button 
            onClick={handleLogout}
            className="px-5 py-2 rounded-lg font-semibold shadow-md transform transition-transform duration-300 ease-in-out bg-red-600 text-white hover:bg-red-700 hover:shadow-lg hover:scale-105"
          >
            Logout
          </button>
          
          <button 
            onClick={() => {
              // Generate and download payment report
              const reportContent = generatePaymentReport();
              const blob = new Blob([reportContent], { type: 'text/plain' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = `payment-report-${workerData?.job_card_id || 'worker'}.txt`;
              document.body.appendChild(a);
              a.click();
              document.body.removeChild(a);
              URL.revokeObjectURL(url);
            }}
            className="px-5 py-2 rounded-lg font-semibold shadow-md transform transition-transform duration-300 ease-in-out bg-green-600 text-white hover:bg-green-700 hover:shadow-lg hover:scale-105"
          >
            Download Report
          </button>
        </div>
      </header>

      <main className="container max-w-7xl mx-auto px-6 py-10">
        {/* Welcome Section */}
        <div className={`rounded-3xl p-8 mb-8 shadow-xl ${isDarkTheme ? 'bg-gray-800/90 backdrop-blur-lg' : 'bg-white/90 backdrop-blur-lg'}`}>
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center">
            <div>
              <h1 className="text-3xl font-bold bg-gradient-to-r from-indigo-700 to-purple-700 bg-clip-text text-transparent">
                Payment Details
              </h1>
              <p className="mt-2 text-lg text-gray-600 dark:text-gray-300">
                Welcome, {workerData?.name || 'Worker'}
              </p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Job Card ID: <span className="font-semibold text-indigo-600">{workerData?.job_card_id || 'N/A'}</span>
              </p>
            </div>
            {workerData?.payment_deadline && (
              <div className={`mt-4 md:mt-0 px-6 py-3 rounded-xl bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-200`}>
                <p className="text-center font-semibold">
                  Next Payment Deadline: {formatDate(workerData?.payment_deadline)}
                </p>
              </div>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Payment Summary */}
          <div className={`lg:col-span-2 rounded-3xl p-8 shadow-xl ${isDarkTheme ? 'bg-gray-800/90 backdrop-blur-lg' : 'bg-white/90 backdrop-blur-lg'}`}>
            <h2 className="text-2xl font-bold mb-6 bg-gradient-to-r from-indigo-700 to-purple-700 bg-clip-text text-transparent">
              Payment Summary
            </h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
              <div className="p-6 rounded-xl bg-green-50 dark:bg-green-900/30">
                <p className="text-sm text-gray-500 dark:text-gray-400">Total Amount Earned</p>
                <p className="text-3xl font-bold text-green-700 dark:text-green-300">
                  ₹{workerData?.total_amount || 0}
                </p>
              </div>
              
              <div className="p-6 rounded-xl bg-blue-50 dark:bg-blue-900/30">
                <p className="text-sm text-gray-500 dark:text-gray-400">Completed Projects</p>
                <p className="text-3xl font-bold text-blue-700 dark:text-blue-300">
                  {workerData?.work_history?.filter((w: any) => w.status === 'completed' || w.status === 'paid').length || 0}
                </p>
              </div>
              
              <div className="p-6 rounded-xl bg-amber-50 dark:bg-amber-900/30">
                <p className="text-sm text-gray-500 dark:text-gray-400">Pending Payments</p>
                <p className="text-3xl font-bold text-amber-700 dark:text-amber-300">
                  {workerData?.work_history?.filter((w: any) => w.status !== 'completed' && w.status !== 'paid').length || 0}
                </p>
              </div>
              
              <div className="p-6 rounded-xl bg-purple-50 dark:bg-purple-900/30">
                <p className="text-sm text-gray-500 dark:text-gray-400">Total Projects</p>
                <p className="text-3xl font-bold text-purple-700 dark:text-purple-300">
                  {workerData?.work_history?.length || 0}
                </p>
              </div>
            </div>

            {/* Monthly Breakdown */}
            {monthlyTotals.length > 0 && (
              <div>
                <h3 className="text-xl font-semibold mb-4 text-indigo-700 dark:text-indigo-300">Monthly Earnings</h3>
                <div className="space-y-3">
                  {monthlyTotals.map((month: any, index: number) => (
                    <div 
                      key={index} 
                      className={`p-4 rounded-lg border ${isDarkTheme ? 'border-gray-700 bg-gray-800' : 'border-gray-200 bg-gray-50'}`}
                    >
                      <div className="flex justify-between items-center">
                        <div>
                          <p className="font-semibold text-lg">{month.month}</p>
                          <p className="text-sm text-gray-500 dark:text-gray-400">
                            {month.projects} project{month.projects !== 1 ? 's' : ''}
                          </p>
                        </div>
                        <p className="text-2xl font-bold text-green-600 dark:text-green-400">
                          ₹{month.totalAmount}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Bank Details */}
          <div className={`rounded-3xl p-8 shadow-xl ${isDarkTheme ? 'bg-gray-800/90 backdrop-blur-lg' : 'bg-white/90 backdrop-blur-lg'}`}>
            <h2 className="text-2xl font-bold mb-6 bg-gradient-to-r from-indigo-700 to-purple-700 bg-clip-text text-transparent">
              Bank Details
            </h2>
            
            {!showBankForm ? (
              <div>
                {workerData?.bank_details ? (
                  <div className="space-y-4">
                    <div>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Bank Name</p>
                      <p className="font-medium">{workerData.bank_details.bank_name || 'N/A'}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Account Number</p>
                      <p className="font-medium">
                        {workerData.bank_details.account_number 
                          ? 'XXXXXX' + workerData.bank_details.account_number.slice(-4)
                          : 'N/A'
                        }
                      </p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500 dark:text-gray-400">IFSC Code</p>
                      <p className="font-medium">{workerData.bank_details.ifsc_code || 'N/A'}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Branch Name</p>
                      <p className="font-medium">{workerData.bank_details.branch_name || 'N/A'}</p>
                    </div>
                    <button
                      onClick={() => setShowBankForm(true)}
                      className="w-full mt-6 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
                    >
                      Update Bank Details
                    </button>
                  </div>
                ) : (
                  <div className="text-center py-8">
                    <p className="text-gray-500 dark:text-gray-400 mb-4">
                      No bank details found
                    </p>
                    <button
                      onClick={() => setShowBankForm(true)}
                      className="px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
                    >
                      Add Bank Details
                    </button>
                  </div>
                )}
              </div>
            ) : (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-1">Bank Name *</label>
                  <input
                    type="text"
                    name="bankName"
                    value={bankDetails.bankName}
                    onChange={handleBankDetailsChange}
                    className={`w-full px-3 py-2 rounded-lg border ${
                      isDarkTheme 
                        ? 'bg-gray-700 border-gray-600 text-white' 
                        : 'bg-white border-gray-300 text-gray-900'
                    }`}
                    placeholder="Enter bank name"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium mb-1">Account Number *</label>
                  <input
                    type="text"
                    name="accountNumber"
                    value={bankDetails.accountNumber}
                    onChange={handleBankDetailsChange}
                    className={`w-full px-3 py-2 rounded-lg border ${
                      isDarkTheme 
                        ? 'bg-gray-700 border-gray-600 text-white' 
                        : 'bg-white border-gray-300 text-gray-900'
                    }`}
                    placeholder="Enter account number"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium mb-1">IFSC Code *</label>
                  <input
                    type="text"
                    name="ifscCode"
                    value={bankDetails.ifscCode}
                    onChange={handleBankDetailsChange}
                    className={`w-full px-3 py-2 rounded-lg border ${
                      isDarkTheme 
                        ? 'bg-gray-700 border-gray-600 text-white' 
                        : 'bg-white border-gray-300 text-gray-900'
                    }`}
                    placeholder="Enter IFSC code"
                    maxLength={11}
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium mb-1">Branch Name</label>
                  <input
                    type="text"
                    name="branchName"
                    value={bankDetails.branchName}
                    onChange={handleBankDetailsChange}
                    className={`w-full px-3 py-2 rounded-lg border ${
                      isDarkTheme 
                        ? 'bg-gray-700 border-gray-600 text-white' 
                        : 'bg-white border-gray-300 text-gray-900'
                    }`}
                    placeholder="Enter branch name"
                  />
                </div>
                
                <div className="flex space-x-3 pt-4">
                  <button
                    onClick={handleUpdateBankDetails}
                    disabled={isUpdating}
                    className="flex-1 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 transition-colors"
                  >
                    {isUpdating ? 'Updating...' : 'Save Details'}
                  </button>
                  <button
                    onClick={() => setShowBankForm(false)}
                    className="flex-1 px-4 py-2 bg-gray-500 text-white rounded-lg hover:bg-gray-600 transition-colors"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Payment History */}
        {workerData?.work_history && workerData.work_history.length > 0 && (
          <div className={`mt-8 rounded-3xl p-8 shadow-xl ${isDarkTheme ? 'bg-gray-800/90 backdrop-blur-lg' : 'bg-white/90 backdrop-blur-lg'}`}>
            <h2 className="text-2xl font-bold mb-6 bg-gradient-to-r from-indigo-700 to-purple-700 bg-clip-text text-transparent">
              Payment History
            </h2>
            
            <div className="space-y-4">
              {workerData.work_history.map((work: any, index: number) => (
                <div 
                  key={index} 
                  className={`p-6 rounded-xl border-l-4 ${
(work.status === 'completed' || work.status === 'paid') 
                      ? 'border-green-500 bg-green-50 dark:bg-green-900/20' 
                      : 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                  }`}
                >
                  <div className="flex flex-col md:flex-row md:justify-between md:items-center">
                    <div className="flex-1">
                      <h3 className="font-bold text-lg">{work.name || work.project_name || 'Unnamed Project'}</h3>
                      <p className="text-gray-600 dark:text-gray-300 mt-1">
                        {formatDate(work.start_date)} to {formatDate(work.end_date)}
                      </p>
                      <p className="text-gray-600 dark:text-gray-300">
                        Wage: ₹{work.wage_per_worker || work.wage || 0}
                      </p>
                    </div>
                    <div className="flex items-center space-x-4 mt-3 md:mt-0">
                      <div className={`px-3 py-1 rounded-full text-sm font-medium ${
(work.status === 'completed' || work.status === 'paid') 
                          ? 'bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-200' 
                          : 'bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-200'
                      }`}>
{(work.status === 'completed' || work.status === 'paid') ? 'Paid' : 'Pending'}
                      </div>
{(work.status === 'completed' || work.status === 'paid') && (
                        <div className="text-sm text-gray-500 dark:text-gray-400">
                          Paid on {formatDate(work.end_date)}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className={`py-8 px-6 mt-12 ${isDarkTheme ? 'bg-gray-900/90 backdrop-blur-lg shadow-xl' : 'bg-white/90 backdrop-blur-lg shadow-xl'} transition-colors duration-300`}>
        <div className="text-center text-gray-600 dark:text-gray-400">
          <p>© 2025 Smart Rozgar Portal. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}